### PR TITLE
add some update type and CreateChatInviteLink 

### PR DESCRIPTION
**Pull request by ABOLFAZLVALIKHANI**
I added the `CreateChatInviteLink` method. 

change name method `kickChatMember` to `banChatMember`
I kept the previous name so that users don't have problems when changing the version

And add multiple `update` types:
`my_chat_member`
`chat_member`
`chat_join_request`

### CODE REVIEW

**Comment by Ali-Toosi** [comment]
Please check out the comments I put in your previous PR @ABOLFAZLVALIKHANI : https://github.com/Ali-Toosi/django-tgbot/pull/20

`ChatInviteLink` is a type in Telegram. I understand there is also a method called `CreateChatInviteLink` but there is also a type called `ChatInviteLink`. See this: https://core.telegram.org/bots/api#chatinvitelink

That means we don't need the assistants folder and the file in there. We just need to create a type for `ChatInviteLink` in the `types` folder.

**Comment by ABOLFAZLVALIKHANI** [comment]
Thanks for your patience,
I understanded and deleted assistant folder. 
Please check my new commit.

**Comment by ABOLFAZLVALIKHANI** [comment]
Thanks for your patience,
I understanded, but I forget to delete assistant folder.
I will Delete it tomorrow

**Comment by Ali-Toosi** [comment]
I'm closing this for now. Feel free to re-open later.

**Pull request closed without merging**
